@echo off
REM Build script for Windows (Windows 10/11)

echo 🪟 Building QR Generator for Windows...

REM Check if we're in the right directory
if not exist "qr_generator.py" (
    echo ❌ Error: qr_generator.py not found. Run this script from the project root directory.
    pause
    exit /b 1
)

REM Create virtual environment if it doesn't exist
if not exist "venv" (
    echo 📦 Creating virtual environment...
    python -m venv venv
)

REM Activate virtual environment
echo 🔧 Activating virtual environment...
call venv\Scripts\activate.bat

REM Upgrade pip and install build requirements
echo 📥 Installing build dependencies...
python -m pip install --upgrade pip
pip install -r requirements.txt
pip install -r build_requirements.txt

REM Clean previous builds
echo 🧹 Cleaning previous builds...
if exist build rmdir /s /q build
if exist dist rmdir /s /q dist
if exist __pycache__ rmdir /s /q __pycache__
for /d /r . %%d in (__pycache__) do @if exist "%%d" rmdir /s /q "%%d"
del /s /q *.pyc 2>nul

REM Build with PyInstaller (primary method)
echo 🔨 Building with PyInstaller...
pyinstaller qr_generator.spec --clean --noconfirm

REM Build with cx_Freeze (alternative method)
echo 🔨 Building with cx_Freeze (alternative)...
python setup.py build

REM Create distribution directory structure
echo 📦 Creating distribution package...
if not exist "dist\QRGenerator-Windows" mkdir "dist\QRGenerator-Windows"
xcopy "dist\QRGenerator\*" "dist\QRGenerator-Windows\" /E /I /Y

REM Create installer directory structure  
echo 📦 Creating installer package...
if not exist "dist\QRGenerator-Installer" mkdir "dist\QRGenerator-Installer"
xcopy "dist\QRGenerator\*" "dist\QRGenerator-Installer\" /E /I /Y

REM Create simple batch launcher
echo @echo off > "dist\QRGenerator-Windows\QRGenerator.bat"
echo cd /d "%%~dp0" >> "dist\QRGenerator-Windows\QRGenerator.bat"
echo start "" "QRGenerator.exe" >> "dist\QRGenerator-Windows\QRGenerator.bat"

REM Create ZIP for distribution
echo 📦 Creating distribution archive...
powershell -command "Compress-Archive -Path 'dist\QRGenerator-Windows\*' -DestinationPath 'dist\QRGenerator-Windows-v2.0.zip' -Force"

REM Create NSIS installer script (if NSIS is available)
echo 📦 Creating installer script...
echo ; QR Generator Pro Windows Installer > dist\installer.nsi
echo ; Generated by build script >> dist\installer.nsi
echo. >> dist\installer.nsi
echo !define APPNAME "QR Generator Pro" >> dist\installer.nsi
echo !define VERSION "2.0.0" >> dist\installer.nsi
echo !define PUBLISHER "QR Generator Pro Team" >> dist\installer.nsi
echo !define DESCRIPTION "Professional QR Code Generation Tool" >> dist\installer.nsi
echo. >> dist\installer.nsi
echo Name "${APPNAME}" >> dist\installer.nsi
echo OutFile "QRGenerator-Setup-v2.0.exe" >> dist\installer.nsi
echo InstallDir "$PROGRAMFILES\${APPNAME}" >> dist\installer.nsi
echo RequestExecutionLevel admin >> dist\installer.nsi
echo. >> dist\installer.nsi
echo Page directory >> dist\installer.nsi
echo Page instfiles >> dist\installer.nsi
echo. >> dist\installer.nsi
echo Section "MainSection" SEC01 >> dist\installer.nsi
echo   SetOutPath "$INSTDIR" >> dist\installer.nsi
echo   File /r "QRGenerator-Installer\*" >> dist\installer.nsi
echo   CreateDirectory "$SMPROGRAMS\${APPNAME}" >> dist\installer.nsi
echo   CreateShortCut "$SMPROGRAMS\${APPNAME}\${APPNAME}.lnk" "$INSTDIR\QRGenerator.exe" >> dist\installer.nsi
echo   CreateShortCut "$DESKTOP\${APPNAME}.lnk" "$INSTDIR\QRGenerator.exe" >> dist\installer.nsi
echo   WriteUninstaller "$INSTDIR\Uninstall.exe" >> dist\installer.nsi
echo SectionEnd >> dist\installer.nsi

REM Show build results
echo.
echo ✅ Build completed successfully!
echo.
echo 📁 Build outputs:
echo    • PyInstaller build: dist\QRGenerator\
echo    • cx_Freeze build: build\exe.win-*\
echo    • Windows package: dist\QRGenerator-Windows-v2.0.zip
echo    • Installer script: dist\installer.nsi
echo.
echo 🚀 To create Windows installer:
echo    1. Install NSIS: https://nsis.sourceforge.io/Download
echo    2. Run: makensis dist\installer.nsi
echo.
echo 📋 To test the build:
echo    dist\QRGenerator\QRGenerator.exe

pause